#####iptv

####
###type
iptv
###分类
iptv
###数据
Agit
##
远程$https://agit.ai/868/dy/raw/commit/30d5c8696e1a39ff5338ba2888c201dc9c82c4da/live.txt
####

####
###type
iptv
###分类
iptv
###数据
蓝鲸直播
##
远程$https://cdn.jsdelivr.net/gh/Cyril0563/lanjing_live@main/TVbox_Free/LIVE/Free/tvbox_live.txt
####

####
###type
iptv
###分类
iptv
###数据
搜索tv
##
远程$https://t.tansuo.tv/tv.txt
####

####
###type
iptv
###分类
iptv
###数据
用心
##
远程$http://hiker.nokia.press/hikerule/rulelist.json?id=5388
####

####
###type
iptv
###分类
iptv
###数据
忧伤的肥羊
##
远程$https://ghproxy.com/https://raw.githubusercontent.com/youshandefeiyang/IPTV/main/main/IPTV.m3u
####

####
###type
iptv
###分类
iptv
###数据
iptv-org
##
远程$https://gitlab.com/iptv-org/iptv/-/raw/master/public/index.country.m3u
####

####
###type
iptv
###分类
iptv
###数据
ks
##
远程$https://1771245847.github.io/ks.txt
####

####
###type
iptv
###分类
iptv
###数据
gh
##
远程$https://cdn.staticaly.com/gh/tvbw/mytv/main/tv88
####

####
###type
iptv
###分类
iptv
###数据
vamoschuck
##
远程$https://raw.fastgit.org/vamoschuck/TV/main/M3U
####

####
###type
iptv
###分类
iptv
###数据
kuukey
##
远程$https://gitcode.net/kuukey/a/-/raw/master/tvlive.txt
####

####
###type
iptv
###分类
iptv
###数据
Ltang
##
远程$https://agit.ai/Ltang/Tvsy/raw/branch/master/TV/shengqi.txt
####

####
###type
iptv
###分类
iptv
###数据
anxwl
##
远程$http://wp.anxwl.cn/down.php/ecbbf8c5e677b8d2f6c938de1da6579c.txt
####

####
###type
iptv
###分类
iptv
###数据
xdl53r
##
远程$https://files.catbox.moe/xdl53r.txt
####

####
###type
iptv
###分类
iptv
###数据
神器每日推送
##
远程$https://xn--m7r412advb92j21st65a.tk/live.txt
####

####
###type
iptv
###分类
iptv
###数据
ray
##
远程$http://home.jundie.top:81/ray/tvlive.txt
####

####
###type
iptv
###分类
iptv
###数据
Cat
##
远程$http://home.jundie.top:81/Cat/tv/live.txt
####

####
###type
iptv
###分类
iptv
###数据
mytv
##
远程$https://9xi4o.tk/sub/mytv.txt
####

####
###type
iptv
###分类
iptv
###数据
maolive
##
远程$https://f.cyao.tk/maolive.txt
####

####
###type
iptv
###分类
iptv
###数据
Yoursmile7
##
远程$https://agit.ai/Yoursmile7/TVBox/raw/branch/master/live.txt
####

####
###type
iptv
###分类
iptv
###数据
mmmgit
##
远程$https://freed.yuanhsing.cf/tv/live.txt
####

####
###type
iptv
###分类
iptv
###数据
0903zh
##
远程$https://agit.ai/138001380000/MHQTV/raw/branch/master/TV/0903zh.txt
####

####
###type
iptv
###分类
iptv
###数据
1001
##
远程$http://home.jundie.top:81/Cat/tv/live.txt
####

####
###type
iptv
###分类
iptv
###数据
1002
##
远程$https://ghproxy.com/https://raw.githubusercontent.com/heroaku/TVboxo/main/tv/bc.txt
####

####
###type
iptv
###分类
iptv
###数据
1003
##
远程$https://raw.fastgit.org/zhanghong1983/TVBOXZY/main/TV/live.txt
####

####
###type
iptv
###分类
iptv
###数据
1004
##
远程$https://9xi4o.tk/sub/mytv.txt
####

####
###type
iptv
###分类
iptv
###数据
1005
##
远程$https://9xi4o.tk/OneClickRun/live.txt
####

####
###type
iptv
###分类
iptv
###数据
1006
##
远程$http://js.134584.xyz/tv/live.txt
####

####
###type
iptv
###分类
iptv
###数据
1007
##
远程$https://freed.yuanhsing.cf/tv/live.txt
####

####
###type
iptv
###分类
iptv
###数据
1008
##
远程$https://ghproxy.com/https://raw.githubusercontent.com/chengxueli818913/maoTV/main/live%20(1).txt
####

####
###type
iptv
###分类
iptv
###数据
1009
##
远程$http://52bsj.vip:81/api/v3/file/get/29902/0ERczI0b_zB.txt?sign=Ds2Yn7J68yEi7aZKJJpu-7MarMqeIB-yJlJ-ddZp2AU%3D%3A0
####

####
###type
iptv
###分类
iptv
###数据
1010
##
远程$https://download.kstore.space/download/2863/live.txt
####

####
###type
iptv
###分类
iptv
###数据
1011
##
远程$http://home.jundie.top:81/ray/tvlive.txt
####

####
###type
iptv
###分类
iptv
###数据
1012
##
远程$http://www.m9527.top/ml.txt
####

####
###type
iptv
###分类
iptv
###数据
1013
##
远程$http://111.67.196.181/mtv/zhibo.txt
####

####
###type
iptv
###分类
iptv
###数据
广播电台
##
远程$https://gcore.jsdelivr.net/gh/imDazui/Tvlist-awesome-m3u-m3u8@master/m3u/广播电台2021.m3u
####

####
###type
iptv
###分类
iptv
###数据
万首MV歌曲
##
远程$http://120.53.102.254/live?url=http://52bsj.vip:98/o5
####

####
###type
iptv
###分类
iptv
###数据
世界杯4K源
##
远程$http://120.53.102.254/live?url=http://52bsj.vip:98/1316
####

####
###type
iptv
###分类
iptv
###数据
🎪4K源
##
远程$http://120.53.102.254/live?url=http://52bsj.vip:98/1315
####

####
###type
iptv
###分类
iptv
###数据
🇨🇳中华直播
##
远程$http://120.53.102.254/live?url=http://52bsj.vip:98/zhzb
####

####
###type
iptv
###分类
iptv
###数据
🌴金秋直播
##
远程$http://120.53.102.254/live?url=http://52bsj.vip:81/api/v3/file/get/62381/jq.txt?sign=qAfuOlrK3gWlYNqmv9-6XLZ5Nmm-M0imNDn2yE1YQlE%3D%3A0
####

####
###type
iptv
###分类
iptv
###数据
曲库mkv
##
远程$https://agit.ai/kafeiliu/GO/raw/commit/b01ec411adc7d274787807337b0759692d8903e7/曲库.txt
####

####
###type
iptv
###分类
iptv
###数据
央视卫视
##
CCTV-1 综合,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225934/index.m3u8?servicetype=1& 
CCTV-2 财经,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225948/index.m3u8?servicetype=1& 
CCTV-3 综艺,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225916/index.m3u8?servicetype=1& 
CCTV-4 中文国际,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225922/index.m3u8?servicetype=1& 
CCTV-5 体育,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225925/index.m3u8?servicetype=1& 
CCTV-6 电影,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225936/index.m3u8?servicetype=1& 
CCTV-7 国防军事,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225892/index.m3u8?servicetype=1& 
CCTV-8 电视剧,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221226001/index.m3u8?servicetype=1& 
CCTV-9 记录,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225939/index.m3u8?servicetype=1& 
CCTV-10 科教,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221226004/index.m3u8?servicetype=1& 
CCTV-11 戏曲,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225895/index.m3u8?servicetype=1& 
CCTV-12 社会与法,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221226013/index.m3u8?servicetype=1& 
CCTV-13 新闻,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221226046/index.m3u8?servicetype=1& 
CCTV-14 少儿,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225901/index.m3u8?servicetype=1& 
CCTV-15 音乐,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225945/index.m3u8?servicetype=1& 
CCTV-16 奥林匹克,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225937/index.m3u8?servicetype=1& 
CCTV-17 农业农村,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225910/index.m3u8?servicetype=1& 
CCTV-5+ 体育赛事,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225621/index.m3u8?servicetype=1& 
咪咕4K,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225863/index.m3u8?servicetype=1& 
纯享4K,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225726/index.m3u8?servicetype=1& 
安徽卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225886/index.m3u8?servicetype=1& 
北京卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225889/index.m3u8?servicetype=1& 
北京冬奥纪实,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225995/index.m3u8?servicetype=1& 
北京卡酷少儿,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225730/index.m3u8?servicetype=1& 
重庆卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225898/index.m3u8?servicetype=1& 
东方卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225942/index.m3u8?servicetype=1& 
东南卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225904/index.m3u8?servicetype=1& 
甘肃卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225764/index.m3u8?servicetype=1& 
广东卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225913/index.m3u8?servicetype=1& 
广东嘉佳卡通,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225797/index.m3u8?servicetype=1& 
广东珠江卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225717/index.m3u8?servicetype=1& 
广东大湾区卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225748/index.m3u8?servicetype=1& 
广西卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225767/index.m3u8?servicetype=1& 
贵州卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225770/index.m3u8?servicetype=1& 
海南卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225752/index.m3u8?servicetype=1& 
河北卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225773/index.m3u8?servicetype=1& 
河南卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225806/index.m3u8?servicetype=1& 
黑龙江卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221226019/index.m3u8?servicetype=1& 
湖北卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225954/index.m3u8?servicetype=1& 
湖南卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225919/index.m3u8?servicetype=1& 
湖南金鹰纪实,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225699/index.m3u8?servicetype=1& 
湖南金鹰卡通,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225702/index.m3u8?servicetype=1& 
吉林卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225678/index.m3u8?servicetype=1& 
江苏卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221226025/index.m3u8?servicetype=1& 
江苏优漫卡通,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225791/index.m3u8?servicetype=1& 
江西卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225957/index.m3u8?servicetype=1& 
辽宁卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221226007/index.m3u8?servicetype=1& 
内蒙古卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225751/index.m3u8?servicetype=1& 
宁夏卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225782/index.m3u8?servicetype=1& 
青海卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225705/index.m3u8?servicetype=1& 
山东卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221226010/index.m3u8?servicetype=1& 
山东教育卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225708/index.m3u8?servicetype=1& 
山西卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225785/index.m3u8?servicetype=1& 
陕西卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225754/index.m3u8?servicetype=1& 
上海哈哈炫动,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225711/index.m3u8?servicetype=1& 
上海纪实人文,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221226016/index.m3u8?servicetype=1& 
深圳卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225951/index.m3u8?servicetype=1& 
四川卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225757/index.m3u8?servicetype=1& 
天津卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221226022/index.m3u8?servicetype=1& 
西藏藏语卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225828/index.m3u8?servicetype=1& 
西藏卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225800/index.m3u8?servicetype=1& 
厦门卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225823/index.m3u8?servicetype=1& 
新疆兵团卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225795/index.m3u8?servicetype=1& 
新疆卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225788/index.m3u8?servicetype=1& 
云南卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225794/index.m3u8?servicetype=1& 
浙江卫视,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225928/index.m3u8?servicetype=1& 
NewTV中国功夫,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225690/index.m3u8?servicetype=1& 
NewTV军事评论,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225749/index.m3u8?servicetype=1& 
NewTV军旅剧场,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225727/index.m3u8?servicetype=1& 
NewTV农业致富,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225687/index.m3u8?servicetype=1& 
NewTV动作电影,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225703/index.m3u8?servicetype=1& 
NewTV古装剧场,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225706/index.m3u8?servicetype=1& 
NewTV家庭剧场,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225743/index.m3u8?servicetype=1& 
NewTV怡伴健康,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225684/index.m3u8?servicetype=1& 
NewTV惊悚悬疑,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225746/index.m3u8?servicetype=1& 
NewTV明星大片,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225733/index.m3u8?servicetype=1& 
NewTV武搏世界,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225758/index.m3u8?servicetype=1& 
NewTV海外剧场,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225763/index.m3u8?servicetype=1& 
NewTV潮妈辣婆,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225709/index.m3u8?servicetype=1& 
NewTV炫舞未来,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225728/index.m3u8?servicetype=1& 
NewTV爱情喜剧,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225698/index.m3u8?servicetype=1& 
NewTV精品体育,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225724/index.m3u8?servicetype=1& 
NewTV精品大剧,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225737/index.m3u8?servicetype=1& 
NewTV精品纪录,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225681/index.m3u8?servicetype=1& 
NewTV金牌综艺,http://cdnrrs.gx.chinamobile.com/PLTV/77777777/224/3221225755/index.m3u8?servicetype=1& 
####

####
###type
iptv
###分类
iptv
###数据
Youtube(播放需VPN)
##
中天新闻,https://www.youtube.com/watch?v=_QbRXRnHMVY
台视新闻,https://www.youtube.com/watch?v=xL0ch83RAK8
三立新闻,https://www.youtube.com/watch?v=EB4g7wecgTI
凤凰资讯台,https://www.youtube.com/watch?v=8ysjF7BCtRE
民视新闻,https://www.youtube.com/watch?v=P8DRJChuQQQ
东森新闻,https://www.youtube.com/watch?v=R2iMq5LKXco
####

####
###type
iptv
###分类
iptv
###数据
随机直播
##
抖音,http://mmitv.top/test/douyin.php?id=top
花椒,http://mmitv.top/test/hjzb.php?id=top
6间房,http://mmitv.top/test/6room.php?id=top
千帆,http://mmitv.top/test/qf56.php?id=top
我秀,http://mmitv.top/test/woxiu.php?id=top
快手,http://mmitv.top/test/ks.php
热歌榜,https://api.uomg.com/api/rand.music?sort=热歌榜
新歌榜,https://api.uomg.com/api/rand.music?sort=新歌榜
飙升榜,https://api.uomg.com/api/rand.music?sort=飙升榜
抖音榜,https://api.uomg.com/api/rand.music?sort=抖音榜
电音榜,https://api.uomg.com/api/rand.music?sort=电音榜
####
#####


#####网页影视站源

####
###type
web
###分类
网页影视站源
###标题
骚火影视
###图片
https://gitcode.net/egwang186/iptv/-/raw/master/onebox/saohuotv.png
###BaseURL
"https://saohuo.vip";
###首页地址
getVar("baseURL")+"/";
###分类地址
getVar("baseURL")+"/list/分类-翻页.html";
###搜索地址
getVar("baseURL")+"/search.php?searchword=关键字&searchtype=&page=翻页";
###rule
##首页规则
var 列表=getVar("源码").match(/<li>[\s]*?<div class="v_img"[\s\S]*?<\/li>/g);var 标题规则=".get(.v_title a).t()";var 地址规则=".get(.v_title a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".get(div.v_note).t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";
##筛选数据
var a="分类+电影=1+电视剧=2+动漫=4+喜剧片=6+爱情片=7+恐怖片=8+动作片=9+科幻片=10+大陆剧=20+TVB=21+韩剧=22+美剧=23+日剧=24";var b="";for(var i=1;i<50;i++){b=b+"+第"+i+"页="+i;}var b="翻页"+b;a+"\n"+b;
##分类规则
var 列表=getVar("源码").match(/<li>[\s]*?<div class="v_img"[\s\S]*?<\/li>/g);var 标题规则=".get(.v_title a).t()";var 地址规则=".get(.v_title a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".get(div.v_note).t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";
##选集规则
var 分类=e2Rex(getVar("源码"),".get(ul#play_link)").match(/<li[\s\S]*?\/li>/g);var 线路=e2Rex(getVar("源码"),".get(ul.from_list)").match(/<li[\s\S]*?\/li>/g);var 简介=e2Rex(getVar("源码"),".get(p.p_txt)");var 列表规则=".get(a)";var 标题规则=".get(li).t()";var 选集规则=".get(a).t()";var 选集地址规则=".get(a).a(href)";
##搜索规则
var 源码=getVar("源码");var 列表=源码.match(/<li>[\s]*?<div class="v_img[\s\S]*?<\/li>/g);if(!列表[0]){var 列表=["网页可能有搜索验证，去网页看看吧"];var 标题规则=".t()";var 地址规则=getVar("baseURL");var 图片规则=".get(img).a(data-original)";var 简介规则="长按网页打开，验证后返回重新搜索即可";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";}else{var 标题规则=".get(.v_title a).t()";var 地址规则=".get(.v_title a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".get(div.v_note).t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE=""};
##搜索翻页
var b="";for(var i=1;i<50;i=i+1){b=b+"+第"+i+"页="+i;}
"翻页"+b;
##免嗅探规则
"web="+getVar("地址");
####

####
###type
web
###分类
网页影视站源
###标题
氢视频
###图片
https://gitcode.net/egwang186/iptv/-/raw/master/onebox/h1080p.png
###BaseURL
"https://h1080p.com";
###首页地址
getVar("baseURL")+"/";
###分类地址
getVar("baseURL")+"/index.php/vod/show/id/分类/page/翻页.html";
###搜索地址
getVar("baseURL")+"/index.php/vod/search/wd/关键字/page/翻页.html";
###rule
##首页规则
var 列表=e2Arr(getVar("源码"),".get(div.swiper-slide)");var 标题规则=".get(div[class~=.*title]).t()";var 地址规则=".get(a).a(href)";var 图片规则=".get(img).a(src).or().get(a).a(style).z2([\\(]\\(.+?\\)[\\)])";var 简介规则=".get(div[class~=.*ins]).t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";
##筛选数据
var a="分类+电影=1+电视剧=2+动漫=3+番剧=28+剧场版=30+综艺=31+内地剧=2/area/内地+港剧=2/area/香港+台剧=2/area/台湾+韩剧=2/area/韩国+日本剧=2/area/日本+美剧=2/area/美国+动作片=1/class/动作+喜剧片=1/class/喜剧+爱情片=1/class/爱情+科幻片=1/class/科幻+恐怖片=1/class/恐怖+剧情片=1/class/剧情";var b="";for(var i=1;i<50;i++){b=b+"+第"+i+"页="+i;}var b="翻页"+b;a+"\n"+b;
##分类规则
var 列表=e2Arr(getVar("源码"),".get(div.module-items a.module-item)");var 标题规则=".get(a).a(title)";var 地址规则=".get(a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";
##选集规则
var 分类=e2Arr(getVar("源码"),".get(div.module-play-list)");var 线路=e2Arr(getVar("源码"),".get(div.module-tab-items .module-tab-item)");var 简介=e2Rex(getVar("源码"),".get(div.module-info-content).t()");var 列表规则=".get(a)";var 标题规则=".t()";var 选集规则=".get(a).t()";var 选集地址规则=".get(a).a(href)";
##搜索规则
var 列表=e2Arr(getVar("源码"),".get(div.module-card-item.module-item)");if(!列表[0]){var 列表=["网页可能有搜索验证，去网页看看吧"];var 标题规则=".t()";var 地址规则=getVar("搜索地址");var 图片规则=".get(img).a(data-original)";var 简介规则="长按网页打开，验证后返回重新搜索即可";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";}else{var 标题规则=".get(div.module-card-item-title a).t()";var 地址规则=".get(a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE=""};
##搜索翻页
var b="";for(var i=1;i<50;i=i+1){b=b+"+第"+i+"页="+i;}
"翻页"+b;
##免嗅探规则
"web="+getVar("地址");
####

####
###type
web
###分类
网页影视站源
###标题
蓝光影院
###图片
https://gitcode.net/egwang186/iptv/-/raw/master/onebox/lgyy.png
###BaseURL
"https://www.lgyy.cc";
###首页地址
getVar("baseURL")+"/";
###分类地址
getVar("baseURL")+"/vodshow/分类--------翻页---.html";
###搜索地址
getVar("baseURL")+"/vodsearch/关键字----------翻页---.html";
###rule
##首页规则
var 列表=e2Arr(getVar("源码"),".get(div.module-items a.module-item)").filter((item,index)=>index%2===0);var 标题规则=".get(a).a(title)";var 地址规则=".get(a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";
##筛选数据
var a="分类+电影=1+电视剧=2+动漫=5+纪录=4+国产剧=13+港台剧=14+日韩剧=15+欧美剧=16+动作片=6+喜剧片=7+爱情片=8+科幻片=9+恐怖片=10+剧情片=11";var b="";for(var i=1;i<50;i++){b=b+"+第"+i+"页="+i;}var b="翻页"+b;a+"\n"+b;
##分类规则
var 列表=e2Arr(getVar("源码"),".get(div.module-items a.module-item)");var 标题规则=".get(a).a(title)";var 地址规则=".get(a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";
##选集规则
var 分类=e2Arr(getVar("源码"),".get(div.module-play-list)");var 线路=e2Arr(getVar("源码"),".get(div.module-tab-items div.module-tab-item)");var 简介=e2Rex(getVar("源码"),".get(div.module-info-content).t()");var 列表规则=".get(a)";var 标题规则=".t()";var 选集规则=".get(a).t()";var 选集地址规则=".get(a).a(href)";
##搜索规则
var 列表=e2Arr(getVar("源码"),".get(div.module-card-item.module-item)");if(!列表[0]){var 列表=["网页可能有搜索验证，去网页看看吧"];var 标题规则=".t()";var 地址规则=getVar("搜索地址");var 图片规则=".get(img).a(data-original)";var 简介规则="长按网页打开，验证后返回重新搜索即可";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";}else{var 标题规则=".get(div.module-card-item-title a).t()";var 地址规则=".get(a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE=""};
##搜索翻页
var b="";for(var i=1;i<50;i=i+1){b=b+"+第"+i+"页="+i;}
"翻页"+b;
##免嗅探规则
"web="+getVar("地址");
####

####
###type
web
###分类
网页影视站源
###标题
555电影
###图片
https://gitcode.net/egwang186/iptv/-/raw/master/onebox/555dy.png
###BaseURL
"https://www.555dy1.com";
###首页地址
getVar("baseURL")+"/";
###分类地址
getVar("baseURL")+"/vodshow/分类-----翻页---.html";
###搜索地址
getVar("baseURL")+"/vodsearch/关键字----------翻页---.html";
###rule
##首页规则
var 列表=e2Arr(getVar("源码"),".get(div.module-items a.module-item)");var 标题规则=".get(a).a(title)";var 地址规则=".get(a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";
##筛选数据
var a="分类+电影=1---+电视剧=2---+福利=124---+动漫=4---+Netflix电影=1---Netflix+Netflix剧=2---Netflix+剧情片=1---剧情+科幻片=1---科幻+动作片=1---动作+喜剧片=1---喜剧+爱情片=1---爱情+大陆剧=2-大陆--+香港剧=2-香港--+韩剧=2-韩国--+美剧=2-美国--+日剧=2-日本--";var b="";for(var i=1;i<50;i++){b=b+"+第"+i+"页="+i;}var b="翻页"+b;a+"\n"+b;
##分类规则
var 列表=e2Arr(getVar("源码"),".get(div.module-items a.module-item)");var 标题规则=".get(a).a(title)";var 地址规则=".get(a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";
##选集规则
var 分类=e2Arr(getVar("源码"),".get(div.module-play-list)");var 线路=e2Arr(getVar("源码"),".get(div.module-tab-items div.module-tab-item)");var 简介=e2Rex(getVar("源码"),".get(div.module-info-content).t()");var 列表规则=".get(a)";var 标题规则=".t()";var 选集规则=".get(a).t()";var 选集地址规则=".get(a).a(href)";
##搜索规则
var 源码=getVar("源码");var 列表=e2Arr(源码,".get(div.module-items div.module-item)");if(!列表[0]){var 列表=["网页可能有搜索验证，去网页看看吧"];var 标题规则=".t()";var 地址规则=getVar("搜索地址");var 图片规则=".get(img).a(data-original)";var 简介规则="长按网页打开，验证后返回重新搜索即可";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";}else{var 标题规则=".get(div.module-card-item-title a).t()";var 地址规则=".get(div.module-card-item-title a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";};
##搜索翻页
var b="";for(var i=1;i<50;i=i+1){b=b+"+第"+i+"页="+i;}
"翻页"+b;
##免嗅探规则
"web="+getVar("地址");
####


###type
web
###分类
网页影视站源
###标题
特狗影视
###图片
https://gitcode.net/egwang186/iptv/-/raw/master/onebox/tegouys.png
###BaseURL
"https://www.tegouys.com";
###首页地址
getVar("baseURL")+"/";
###分类地址
getVar("baseURL")+"/vodshow/id/分类/page/翻页.html";
###搜索地址
getVar("baseURL")+"/vodsearch/page/翻页/wd/关键字.html";
###rule
##首页规则
var 列表=e2Arr(getVar("源码"),".get(ul.myui-vodlist li)");var 标题规则=".get(.title a).t()";var 地址规则=".get(.title a).a(href)";var 图片规则=".get(a).a(data-original)";var 简介规则=".get(span).st().t().c().get(p).t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";
##筛选数据
var a="分类+电影=1+电视剧=2+综艺=3+动漫=4+纪录片=5+动作片=1/class/动作+喜剧片=1/class/喜剧+爱情片=1/class/爱情+科幻片=1/class/科幻+恐怖片=1/class/恐怖+剧情片=1/class/剧情+国产剧=2/class/国产+港台剧=2/class/港台+日韩剧=2/class/日韩+美剧=2/class/美国+大陆剧=2/area/中国大陆+香港剧=2/area/中国香港+台湾剧=2/area/中国台湾+韩剧=2/area/韩国+日本剧=2/area/日本+美国剧=2/area/美国";var b="";for(var i=1;i<50;i++){b=b+"+第"+i+"页="+i;}var b="翻页"+b;a+"\n"+b;
##分类规则
var 列表=e2Arr(getVar("源码"),".get(ul.myui-vodlist li)");var 标题规则=".get(.title a).t()";var 地址规则=".get(.title a).a(href)";var 图片规则=".get(a).a(data-original)";var 简介规则=".get(span).st().t().c().get(p).t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";
##选集规则
var 分类=e2Arr(getVar("源码"),".get(ul.myui-content__list)");var 简介=e2Rex(getVar("源码"),".get(div.myui-content__detail).t()");var 线路=e2Arr(getVar("源码"),".get(ul.nav.nav-tabs li)");var 列表规则=".get(li)";var 标题规则=".get(a).t()";var 选集规则=".get(a).t()";var 选集地址规则=".get(a).a(href)";
##搜索规则
var 源码=getVar("源码");var 列表=e2Arr(源码,".get(ul.myui-vodlist__media li)");if(!列表[0]){var 列表=["网页可能有搜索验证，去网页看看吧"];var 标题规则=".t()";var 地址规则=getVar("搜索地址");var 图片规则=".get(img).a(data-original)";var 简介规则="长按网页打开，验证后返回重新搜索即可";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";}else{var 标题规则=".get(.title a).t()";var 地址规则=".get(.title a).a(href)";var 图片规则=".get(a).a(data-original)";var 简介规则=".t()";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE=""};
##搜索翻页
var b="";for(var i=1;i<50;i=i+1){b=b+"+第"+i+"页="+i;}
"翻页"+b;
##免嗅探规则
"web="+getVar("地址");


####
###type
web
###分类
网页影视站源
###标题
虎牙直播
###图片
https://gitcode.net/egwang186/iptv/-/raw/master/onebox/huya.png
###BaseURL
"https://m.huya.com";
###首页地址
"https://live.cdn.huya.com/liveHttpUI/getHomeLiveRecommend?iType=1&ePlatform=1";
###分类地址
"https://www.huya.com/cache.php?m=LiveList&do=getLiveListByPage&gameId=分类&tagAll=0&callback=getLiveListJsonpCallback&page=翻页";
###搜索地址
"https://search.cdn.huya.com/?m=Search&do=getSearchContent&q=关键字&uid=0&v=4&typ=-5&livestate=0&rows=翻页";
###rule
##首页规则
var 列表=getVar("源码").replace(/\s+/g,"").match(/\{"lUid"[^\{]+?sRoomName.+?sRecommendTagName.+?\}/g);var 标题规则=".json(sRoomName)";var 地址规则=".c(/).json(lProfileRoom)";var 图片规则=".json(sScreenshot)";var 简介规则=".json(sIntroduction)";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";
##筛选数据
var a="分类+全部=+一起看=2135+原神=5489+英雄联盟手游=6203+英雄联盟=1+王者荣耀=2336+和平精英=3203+天天吃鸡=2793+穿越火线=4+棋牌桌游=100036+颜值=2168+交友=4079+放映厅=6245+互动点播=5907+音乐=3793+体育=2356";var b="";for(var i=1;i<50;i++){b=b+"+第"+i+"页="+i;}var b="翻页"+b;a+"\n"+b;
##分类规则
var 列表=e2Arr(getVar("源码").replace(/\s+/g,""),".z(\\{.+).json(data).json(datas)");var 标题规则=".json(roomName)";var 地址规则=".c(/).json(profileRoom)";var 图片规则=".json(screenshot)";var 简介规则=".json(introduction)";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";
##选集规则
var 标识=e2Rex(getVar("源码"),".ty(HNF_GLOBAL_INIT)").match(/"sStreamName":"(.+?)"/)[1];var 分类=[];var a={};var data=[];data.push({name:"P2p线路",url:"http://txtest-xp2p.p2p.huya.com/src/"+标识+".xs"},{name:"Hw.hls线路",url:"https://hw.hls.huya.com/src/"+标识+".m3u8"},{name:"Txdirect.hls线路",url:"http://36.101.206.161/txdirect.hls.huya.com/src/"+标识+".m3u8"},{name:"Tx.hls线路",url:"http://121.51.249.48/tx.hls.huya.com/src/"+标识+".m3u8"});a.data=data;a.title="线路";分类.push(a);var 分类=e2Arr(JSON.stringify(分类),".json()");var 线路="";var 简介=e2Rex(getVar("name"),".t()");var 列表规则=".json(data)";var 标题规则=".json(title)";var 选集规则=".json(name)";var 选集地址规则=".json(url)";
##搜索规则
var 源码=getVar("源码");var 列表=e2Arr(源码,".json(response).json(3).json(docs)");if(!列表[0]){var 列表=["网页可能有搜索验证，去网页看看吧"];var 标题规则=".t()";var 地址规则=getVar("搜索地址");var 图片规则=".get(img).a(data-original)";var 简介规则="长按网页打开，验证后返回重新搜索即可";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE="";}else{var 标题规则=".json(game_roomName)";var 地址规则=".c(/).json(room_id)";var 图片规则=".json(game_screenshot)";var 简介规则=".json(game_introduction)";var 图片底部规则="";var 左上规则="";var 右上规则="";var NEXTPAGE="";var PREPAGE=""};
##搜索翻页
var b="";for(var i=40;i<1000;i=i+40){b=b+"+第"+i+"页="+i;}
"翻页"+b;
##免嗅探规则
JSON.stringify({name:"地址",url:getVar("地址")});
####

#####
